src/main/java/com/nmnm/dto/CommunicationBoard.java
src/main/java/com/nmnm/dto/CommunicationBoardLike.java
src/main/java/com/nmnm/dto/CommunicationBoardPhoto.java
src/main/java/com/nmnm/dto/CommunicationBoardReply.java

dto 폴더에 CommunicationBoard, CommunicationBoardLike,
CommunicationBoardReply, CommunicationBoardPhoto 클래스 추가

[add] communication board dto 추가

---

src/main/java/com/nmnm/dto/Account.java
src/main/java/com/nmnm/dto/AccountAuthority.java
src/main/java/com/nmnm/dto/AccountType.java
src/main/java/com/nmnm/dto/Alram.java
src/main/java/com/nmnm/dto/Message.java

Account.java 추가
AccountAuthority.java 추가
AccountType.java 추가
Alram.java 추가
Message.java 추가

[add] 회계 관련 및 알람, 메시지 DTO 추가

---

src/main/java/com/nmnm/dto/Grade.java
src/main/java/com/nmnm/dto/Group.java
src/main/java/com/nmnm/dto/GroupMember.java
src/main/java/com/nmnm/dto/Member.java

Grade dto, Group dto, GroupMember dto, Member dto 추가

[add] 회원,모임 관련 dto 추가

---

src/main/java/com/nmnm/gms/domain/Notice.java
src/main/java/com/nmnm/gms/domain/NoticeAuthority.java
src/main/java/com/nmnm/gms/domain/NoticePhoto.java
src/main/java/com/nmnm/gms/domain/NoticeReply.java
src/main/java/com/nmnm/gms/domain/WriteAuthority.java

Notice.java
NoticeAuthority.java
NoticePhoto.java
NoticeReply.java
WriteAuthority.java
도메인 추가

[add] 공지사항 및 글 작성 권한 관련 도메인 추가

---

src/main/java/com/nmnm/gms/DatabaseConfig.java
src/main/java/com/nmnm/gms/dao/NoticeDao.java
src/main/java/com/nmnm/gms/domain/Notice.java
src/main/java/com/nmnm/gms/domain/NoticeAuthority.java
src/main/java/com/nmnm/gms/domain/NoticePhoto.java
src/main/java/com/nmnm/gms/domain/NoticeReply.java
src/main/java/com/nmnm/gms/domain/WriteAuthority.java
src/main/java/com/nmnm/gms/service/NoticeService.java
src/main/java/com/nmnm/gms/service/impl/NoticeServiceImpl.java
src/main/java/com/nmnm/gms/web/AppWebApplicationInitializer.java
src/main/java/com/nmnm/gms/web/NoticeController.java
src/main/resources/com/nmnm/gms/conf/jdbc.properties
src/main/resources/com/nmnm/gms/log4j2.xml
src/main/resources/com/nmnm/gms/mapper/NoticeMapper.xml
src/main/webapp/WEB-INF/jsp/header.jsp
src/main/webapp/WEB-INF/jsp/notice/detail.jsp
src/main/webapp/WEB-INF/jsp/notice/form.jsp
src/main/webapp/WEB-INF/jsp/notice/list.jsp
src/main/webapp/WEB-INF/jsp/notice/updateForm.jsp
src/main/webapp/index.html

/dao/NoticeDao.java
/NoticeService.java
/service/impl/NoticeServiceImpl.java
/web/NoticeController.java
/mapper/NoticeMapper.xml
/webapp/WEB-INF/jsp/notice/detail.jsp
/webapp/WEB-INF/jsp/notice/form.jsp
/webapp/WEB-INF/jsp/notice/list.jsp
/webapp/WEB-INF/jsp/notice/updateForm.jsp
추가

[add] notice 관련 파일 추가

---

src/main/java/com/nmnm/gms/dao/FeedDao.java
src/main/resources/com/nmnm/gms/mapper/FeedMapper.xml
src/main/webapp/WEB-INF/jsp/feed/detail.jsp
src/main/webapp/WEB-INF/jsp/feed/form.jsp
src/main/webapp/WEB-INF/jsp/feed/list.jsp
src/main/webapp/WEB-INF/jsp/feedPhoto/detail.jsp
src/main/webapp/WEB-INF/jsp/feedPhoto/form.jsp
src/main/webapp/WEB-INF/jsp/feedPhoto/list.jsp
src/main/webapp/WEB-INF/jsp/header.jsp

java - FeedDao
resources - FeedMapper
webapp - feed, feedphoto

[add] feed 관련 파일 추가

---

src/main/java/com/nmnm/gms/dao/PlanDao.java
src/main/java/com/nmnm/gms/domain/Plan.java
src/main/java/com/nmnm/gms/service/PlanService.java
src/main/java/com/nmnm/gms/service/impl/PlanServiceImpl.java
src/main/java/com/nmnm/gms/web/PlanController.java
src/main/resources/com/nmnm/gms/log4j2.xml
src/main/resources/com/nmnm/gms/mapper/PlanMapper.xml
src/main/webapp/WEB-INF/jsp/header.jsp
src/main/webapp/WEB-INF/jsp/plan/detail.jsp
src/main/webapp/WEB-INF/jsp/plan/form.jsp
src/main/webapp/WEB-INF/jsp/plan/list.jsp
src/main/webapp/index.html

dao/PlanDao.java 추가, service/PlanService.java 추가, service/impl/PlanServiceImpl.java 추가,
web/PlanController.java 추가
/mapper/PlanMapper.xml 추가,
/WEB-INF/jsp/plan/detail.jsp 추가
/WEB-INF/jsp/plan/form.jsp 추가
/WEB-INF/jsp/plan/list.jsp 추가

[add] 일정 상세보기, 업데이트, 삭제 기능 구현

---

src/main/webapp/WEB-INF/jsp/error.jsp
src/main/webapp/WEB-INF/jsp/footer.jsp
src/main/webapp/WEB-INF/jsp/header.jsp
src/main/webapp/index.html

index.html, header.jsp 수정 및 footer.jsp, error.jsp 복구

[mod] index.html, header.jsp 수정

---

src/main/java/com/nmnm/gms/dao/CommunicationBoardDao.java
src/main/java/com/nmnm/gms/service/CommunicationBoardService.java
src/main/java/com/nmnm/gms/service/impl/CommunicationBoardServiceImpl.java
src/main/java/com/nmnm/gms/web/CommunicationBoardController.java
src/main/resources/com/nmnm/gms/mapper/CommunicationBoardMapper.xml
src/main/webapp/WEB-INF/jsp/communicationBoard/detail.jsp
src/main/webapp/WEB-INF/jsp/communicationBoard/form.jsp
src/main/webapp/WEB-INF/jsp/communicationBoard/search.jsp
src/main/webapp/WEB-INF/jsp/communicationBoard/updateForm.jsp

CommunicationBoardService.java 수정
CommunicationBoardController.java 수정
CommunicationBoardMapper.xml 수정
search.jsp 추가

[add] 소통게시판 검색기능 추가

---

src/main/java/com/nmnm/gms/domain/Feed.java
src/main/resources/com/nmnm/gms/mapper/FeedMapper.xml
src/main/webapp/WEB-INF/jsp/feed/list.jsp

수정한 데이터베이스에 맞게 feed domain 과 mapper등 컬럼 적용

[mod] feed 관련 데이터베이스 수정 적용

---

src/main/java/com/nmnm/gms/dao/NoticeDao.java
src/main/java/com/nmnm/gms/domain/Notice.java
src/main/java/com/nmnm/gms/service/NoticeService.java
src/main/java/com/nmnm/gms/service/impl/NoticeServiceImpl.java
src/main/java/com/nmnm/gms/web/NoticeController.java
src/main/resources/com/nmnm/gms/mapper/NoticeMapper.xml
src/main/webapp/WEB-INF/jsp/notice/detail.jsp
src/main/webapp/WEB-INF/jsp/notice/form.jsp
src/main/webapp/WEB-INF/jsp/notice/list.jsp
src/main/webapp/WEB-INF/jsp/notice/updateForm.jsp

[mod] 공지사항 list 구현

---

src/main/java/com/nmnm/gms/dao/FeedDao.java
src/main/java/com/nmnm/gms/service/FeedService.java
src/main/java/com/nmnm/gms/service/impl/FeedServiceImpl.java
src/main/java/com/nmnm/gms/web/FeedController.java
src/main/resources/com/nmnm/gms/mapper/FeedMapper.xml
src/main/webapp/WEB-INF/jsp/feed/detail.jsp
src/main/webapp/WEB-INF/jsp/feed/form.jsp
src/main/webapp/WEB-INF/jsp/feed/list.jsp
src/main/webapp/WEB-INF/jsp/feed/search.jsp

feed search 기능 추가를 위한 mapper, jsp, controller, dao, service 수정

[mod] feed search 기능 추가

---

src/main/resources/com/nmnm/gms/mapper/PlanMapper.xml
src/main/webapp/WEB-INF/jsp/plan/search.jsp

[mod] 일정 게시판 검색 기능 수정

---

src/main/java/com/nmnm/gms/dao/AccountDao.java
src/main/java/com/nmnm/gms/domain/Account.java
src/main/java/com/nmnm/gms/service/AccountService.java
src/main/java/com/nmnm/gms/service/impl/AccountServiceImpl.java
src/main/java/com/nmnm/gms/web/AccountController.java
src/main/resources/com/nmnm/gms/mapper/AccountMapper.xml
src/main/resources/com/nmnm/gms/mapper/NoticeMapper.xml
src/main/webapp/WEB-INF/jsp/account/detail.jsp
src/main/webapp/WEB-INF/jsp/account/form.jsp
src/main/webapp/WEB-INF/jsp/account/list.jsp
src/main/webapp/WEB-INF/jsp/account/updateForm.jsp
src/main/webapp/WEB-INF/jsp/header.jsp
src/main/webapp/WEB-INF/jsp/notice/form.jsp
src/main/webapp/WEB-INF/jsp/notice/updateForm.jsp
src/main/webapp/index.html

-java/dao/AccountDao.java
-java/service/AccountService.java
-java/service/impl/AccountServiceImpl.java
-java/web/AccountController.java
-resource/mapper/AccountMapper.xml
-webapp/WEB-INF/account/detail, form, list, updateForm.jsp
추가
Notice 변경, 추가 기능 구현

[add] account 추가 및 notice 수정

---

src/main/resources/com/nmnm/gms/mapper/CommunicationBoardMapper.xml
src/main/webapp/WEB-INF/jsp/communicationBoard/categorySearch.jsp
src/main/webapp/WEB-INF/jsp/communicationBoard/list.jsp
src/main/webapp/WEB-INF/jsp/communicationBoard/search.jsp

[mod] 소통게시판 글 분류 방식 적용

---

src/main/webapp/WEB-INF/jsp/communicationBoard/categorySearch.jsp
src/main/webapp/WEB-INF/jsp/communicationBoard/list.jsp

[mod] 소통게시판 글 분류 수정

---

src/main/java/com/nmnm/gms/Criteria.java
src/main/java/com/nmnm/gms/PagingInfo.java
src/main/java/com/nmnm/gms/dao/CommunicationBoardDao.java
src/main/java/com/nmnm/gms/web/CommunicationBoardController.java
src/main/resources/com/nmnm/gms/mapper/CommunicationBoardMapper.xml
src/main/webapp/WEB-INF/jsp/communicationBoard/categorySearch.jsp
src/main/webapp/WEB-INF/jsp/communicationBoard/list.jsp
src/main/webapp/WEB-INF/jsp/header.jsp

페이징 처리 관련 파일 추가 및 수정
UI 수정
div.container width 길이 확장 700px -> 1000px (header.jsp)

[add] 소통게시판 내 페이징 처리 css만 구현

---

src/main/webapp/WEB-INF/jsp/header.jsp
src/main/webapp/index.html

[mod] header.jsp index.html 수정

---

src/main/java/com/nmnm/gms/dao/MemberDao.java
src/main/java/com/nmnm/gms/service/MemberService.java
src/main/java/com/nmnm/gms/service/impl/MemberServiceImpl.java
src/main/java/com/nmnm/gms/web/AuthController.java
src/main/resources/com/nmnm/gms/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/jsp/auth/join.jsp

수정함:        src/main/java/com/nmnm/gms/dao/MemberDao.java
수정함:        src/main/java/com/nmnm/gms/service/MemberService.java
수정함:        src/main/java/com/nmnm/gms/service/impl/MemberServiceImpl.java
수정함:        src/main/java/com/nmnm/gms/web/AuthController.java
수정함:        src/main/resources/com/nmnm/gms/mapper/MemberMapper.xml
수정함:        src/main/webapp/WEB-INF/jsp/auth/join.jsp

[mod] 회원가입시 닉네임 중복확인 추가

---

src/main/java/com/nmnm/gms/domain/Feed.java
src/main/java/com/nmnm/gms/web/FeedController.java
src/main/webapp/WEB-INF/jsp/footer.jsp
src/main/webapp/WEB-INF/jsp/header.jsp
src/main/webapp/WEB-INF/jsp/notice/detail.jsp
src/main/webapp/WEB-INF/jsp/notice/form.jsp
src/main/webapp/WEB-INF/jsp/notice/list.jsp
src/main/webapp/WEB-INF/jsp/notice/updateForm.jsp

[mod] notice CRUD 수정

---

src/main/java/com/nmnm/gms/MailConfig.java
src/main/java/com/nmnm/gms/service/MailSendService.java
src/main/java/com/nmnm/gms/service/impl/MailSendServiceImpl.java
src/main/java/com/nmnm/gms/service/impl/MemberServiceImpl.java
src/main/java/com/nmnm/gms/web/AuthController.java

수정함:        src/main/java/com/nmnm/gms/MailConfig.java
수정함:        src/main/java/com/nmnm/gms/service/MailSendService.java
수정함:        src/main/java/com/nmnm/gms/service/impl/MailSendServiceImpl.java
수정함:        src/main/java/com/nmnm/gms/service/impl/MemberServiceImpl.java
수정함:        src/main/java/com/nmnm/gms/web/AuthController.java

[add] 회원가입 이메일 인증 추가

---

src/main/java/com/nmnm/gms/service/FeedService.java
src/main/java/com/nmnm/gms/web/FeedController.java
src/main/resources/com/nmnm/gms/mapper/FeedMapper.xml
src/main/resources/com/nmnm/gms/mapper/NoticeMapper.xml
src/main/webapp/WEB-INF/jsp/feed/detail.jsp
src/main/webapp/WEB-INF/jsp/feed/form.jsp
src/main/webapp/WEB-INF/jsp/feed/list.jsp
src/main/webapp/WEB-INF/jsp/feed/updateForm.jsp
src/main/webapp/WEB-INF/jsp/notice/list.jsp

feed 피드게시판 list, detail, add, delete 구현

[mod] feed 피드 list, detail, add, delete 구현

---

src/main/webapp/WEB-INF/tiles/template.jsp
src/main/webapp/WEB-INF/views/notice/list.jsp

[mod] tiles폴더 내 template.jsp 라이브러리, 링크 절대 경로로 수정

[mod] tiles폴더 내 template.jsp 절대경로로 수정

---

src/main/webapp/WEB-INF/defs/tiles.xml
src/main/webapp/WEB-INF/tiles/header-old2.jsp
src/main/webapp/WEB-INF/tiles/header.jsp
src/main/webapp/WEB-INF/tiles/template-old2.jsp
src/main/webapp/WEB-INF/views/account/side.jsp
src/main/webapp/WEB-INF/views/auth/side.jsp
src/main/webapp/WEB-INF/views/co/side.jsp
src/main/webapp/WEB-INF/views/feed/side.jsp
src/main/webapp/WEB-INF/views/grmember/side.jsp
src/main/webapp/WEB-INF/views/group/side.jsp
src/main/webapp/WEB-INF/views/member/list.jsp
src/main/webapp/WEB-INF/views/member/side.jsp
src/main/webapp/WEB-INF/views/notice/side.jsp
src/main/webapp/WEB-INF/views/plan/side.jsp
src/main/webapp/css/common.css
src/main/webapp/index.html
src/main/webapp/moim-index.html

[add] views/* 각 폴더에 side.jsp생성
[mod] tiles/template.jsp 수정
[mod] views/member/list.jsp 임시 수정
*바디부분은 /views/notice/list.jsp 형식 참고하세요.

[add] views/* 각 폴더에 side.jsp생성

---

build.gradle
src/main/resources/com/nmnm/gms/mapper/AccountMapper.xml
src/main/webapp/WEB-INF/views/account/list.jsp
src/main/webapp/WEB-INF/views/account/search.jsp

[mod] build.gradle 변경

---

src/main/resources/com/nmnm/gms/mapper/NoticeMapper.xml

[add] noticemapper 추가

---

src/main/resources/com/nmnm/gms/mapper/CoMapper.xml

[merge] Comapper 파일 수동 merge

---

src/main/webapp/WEB-INF/views/group/listByJoin.jsp

[mod] 경로 수정
